spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/imagelite
    username: postgres
    password: postgres

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/imagelite